server dynamic-clients {
    authorize {
        if ("%{sql:SELECT secret FROM nas WHERE nasname='%{Client-IP-Address}'}") {
            update control {
                &control:FreeRADIUS-Client-Secret := "%{sql:SELECT secret FROM nas WHERE nasname='%{Client-IP-Address}'}"
            }
        }
        else {
            if ("%{sql:SELECT secret FROM nas WHERE nasname='%{NAS-Identifier}'}") {
                update control {
                    &control:FreeRADIUS-Client-Secret := "%{sql:SELECT secret FROM nas WHERE nasname='%{NAS-Identifier}'}"
                }
            }
            else {
                reject
            }
        }
    }
}